//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaybillCost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int waybillid { get; set; }
        public string cpnumber { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public string housenumber { get; set; }
        public string street { get; set; }
        public string barangay { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
    }
}
