//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaybillCost
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WayBillDbContext : DbContext
    {
        public WayBillDbContext()
            : base("name=WayBillDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WayBill> WayBills { get; set; }
        public virtual DbSet<WeightCost> WeightCosts { get; set; }
        public virtual DbSet<Destination> Destinations { get; set; }
        public virtual DbSet<Origin> Origins { get; set; }
    }
}
