//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaybillCost
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightCost
    {
        public int weightid { get; set; }
        public string priority { get; set; }
        public string type { get; set; }
        public Nullable<int> minweight { get; set; }
        public Nullable<int> maxweight { get; set; }
        public Nullable<decimal> cost { get; set; }
    }
}
